version: '3.9'

services:
  db:
    container_name: db
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRESQL_USERNAME: crm
      POSTGRESQL_PASSWORD: crm
      POSTGRESQL_DATABASE: crm
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/bitnami/postgresql
    networks:
      - mynetwork

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  pgdata: {}

networks:
  mynetwork:
    driver: bridge